
FROM node:18

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia solo el package.json para instalar dependencias primero
COPY package.json ./

# Instala las dependencias del proyecto
RUN npm install

# Copia el resto de los archivos del proyecto
COPY . ./

# Compila la aplicación para producción
RUN npm run build

# Expone el puerto 3000 (puerto por defecto en Next.js)
EXPOSE 3000

# Comando para arrancar la app en producción
CMD ["npm", "start"]